sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t arahman/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true arahman/docker-react npm run test